export const CUSTOMER_LIST_REQUEST = "CUSTOMER_LIST_REQUEST";
export const CUSTOMER_LIST_SUCCESS = "CUSTOMER_LIST_SUCCESS";
export const CUSTOMER_LIST_FAIL = "CUSTOMER_LIST_FAIL";

export const CUSTOMER_LIST_FOR_TRAINER_REQUEST = "CUSTOMER_LIST_FOR_TRAINER_REQUEST";
export const CUSTOMER_LIST_FOR_TRAINER_SUCCESS = "CUSTOMER_LIST_FOR_TRAINER_SUCCESS";
export const CUSTOMER_LIST_FOR_TRAINER_FAIL = "CUSTOMER_LIST_FOR_TRAINER_FAIL";

export const CUSTOMER_LOGIN_REQUEST = "CUSTOMER_LOGIN_REQUEST";
export const CUSTOMER_LOGIN_SUCCESS = "CUSTOMER_LOGIN_SUCCESS";
export const CUSTOMER_LOGIN_FAIL = "CUSTOMER_LOGIN_FAIL";
export const CUSTOMER_LOGOUT = "CUSTOMER_LOGOUT";

export const CUSTOMER_REGISTER_REQUEST = "CUSTOMER_REGISTER_REQUEST";
export const CUSTOMER_REGISTER_SUCCESS = "CUSTOMER_REGISTER_SUCCESS";
export const CUSTOMER_REGISTER_FAIL = "CUSTOMER_REGISTER_FAIL";

export const CUSTOMER_VIEW_REQUEST = "CUSTOMER_VIEW_REQUEST";
export const CUSTOMER_VIEW_SUCCESS = "CUSTOMER_VIEW_SUCCESS";
export const CUSTOMER_VIEW_FAIL = "CUSTOMER_VIEW_FAIL";

export const CUSTOMER_UPDATE_REQUEST = "CUSTOMER_UPDATE_REQUEST";
export const CUSTOMER_UPDATE_SUCCESS = "CUSTOMER_UPDATE_SUCCESS";
export const CUSTOMER_UPDATE_FAIL = "CUSTOMER_UPDATE_FAIL";

export const CUSTOMER_DELETE_REQUEST = "CUSTOMER_DELETE_REQUEST";
export const CUSTOMER_DELETE_SUCCESS = "CUSTOMER_DELETE_SUCCESS";
export const CUSTOMER_DELETE_FAIL = "CUSTOMER_DELETE_FAIL";

export const CUSTOMER_VIEW_BY_ID_REQUEST = "CUSTOMER_VIEW_BY_ID_REQUEST";
export const CUSTOMER_VIEW_BY_ID_SUCCESS = "CUSTOMER_VIEW_BY_ID_SUCCESS";
export const CUSTOMER_VIEW_BY_ID_FAIL = "CUSTOMER_VIEW_BY_ID_FAIL";

export const CUSTOMER_UPDATE_BY_ID_REQUEST = "CUSTOMER_UPDATE_BY_ID_REQUEST";
export const CUSTOMER_UPDATE_BY_ID_SUCCESS = "CUSTOMER_UPDATE_BY_ID_SUCCESS";
export const CUSTOMER_UPDATE_BY_ID_FAIL = "CUSTOMER_UPDATE_BY_ID_FAIL";
