export const FAQ_LIST_CUSTOMER_REQUEST = "FAQ_LIST_CUSTOMER_REQUEST";
export const FAQ_LIST_CUSTOMER_SUCCESS = "FAQ_LIST_CUSTOMER_SUCCESS";
export const FAQ_LIST_CUSTOMER_FAIL = "FAQ_LIST_CUSTOMER_FAIL";

export const FAQ_CREATE_CUSTOMER_REQUEST = "FAQ_CREATE_CUSTOMER_REQUEST";
export const FAQ_CREATE_CUSTOMER_SUCCESS = "FAQ_CREATE_CUSTOMER_SUCCESS";
export const FAQ_CREATE_CUSTOMER_FAIL = "FAQ_CREATE_CUSTOMER_FAIL";

export const FAQ_UPDATE_CUSTOMER_REQUEST = "FAQ_UPDATE_CUSTOMER_REQUEST";
export const FAQ_UPDATE_CUSTOMER_SUCCESS = "FAQ_UPDATE_CUSTOMER_SUCCESS";
export const FAQ_UPDATE_CUSTOMER_FAIL = "FAQ_UPDATE_CUSTOMER_FAIL";

export const FAQ_DELETE_CUSTOMER_REQUEST = "FAQ_DELETE_CUSTOMER_REQUEST";
export const FAQ_DELETE_CUSTOMER_SUCCESS = "FAQ_DELETE_CUSTOMER_SUCCESS";
export const FAQ_DELETE_CUSTOMER_FAIL = "FAQ_DELETE_CUSTOMER_FAIL";

export const FAQ_LIST_TRAINER_REQUEST = "FAQ_LIST_TRAINER_REQUEST";
export const FAQ_LIST_TRAINER_SUCCESS = "FAQ_LIST_TRAINER_SUCCESS";
export const FAQ_LIST_TRAINER_FAIL = "FAQ_LIST_TRAINER_FAIL";

export const FAQ_UPDATE_TRAINER_REQUEST = "FAQ_UPDATE_TRAINER_REQUEST";
export const FAQ_UPDATE_TRAINER_SUCCESS = "FAQ_UPDATE_TRAINER_SUCCESS";
export const FAQ_UPDATE_TRAINER_FAIL = "FAQ_UPDATE_TRAINER_FAIL";
