export const TRAINER_LEAVE_LIST_REQUEST = "TRAINER_LEAVE_LIST_REQUEST";
export const TRAINER_LEAVE_LIST_SUCCESS = "TRAINER_LEAVE_LIST_SUCCESS";
export const TRAINER_LEAVE_LIST_FAIL = "TRAINER_LEAVE_LIST_FAIL";

export const TRAINER_LEAVE_CREATE_REQUEST = "TRAINER_LEAVE_CREATE_REQUEST";
export const TRAINER_LEAVE_CREATE_SUCCESS = "TRAINER_LEAVE_CREATE_SUCCESS";
export const TRAINER_LEAVE_CREATE_FAIL = "TRAINER_LEAVE_CREATE_FAIL";

export const TRAINER_LEAVE_UPDATE_REQUEST = "TRAINER_LEAVE_UPDATE_REQUEST";
export const TRAINER_LEAVE_UPDATE_SUCCESS = "TRAINER_LEAVE_UPDATE_SUCCESS";
export const TRAINER_LEAVE_UPDATE_FAIL = "TRAINER_LEAVE_UPDATE_FAIL";

export const TRAINER_LEAVE_DELETE_REQUEST = "TRAINER_LEAVE_DELETE_REQUEST";
export const TRAINER_LEAVE_DELETE_SUCCESS = "TRAINER_LEAVE_DELETE_SUCCESS";
export const TRAINER_LEAVE_DELETE_FAIL = "TRAINER_LEAVE_DELETE_FAIL";

export const ADMIN_CONFIRM_LEAVE_LIST_REQUEST = "ADMIN_CONFIRM_LEAVE_LIST_REQUEST";
export const ADMIN_CONFIRM_LEAVE_LIST_SUCCESS = "ADMIN_CONFIRM_LEAVE_LIST_SUCCESS";
export const ADMIN_CONFIRM_LEAVE_LIST_FAIL = "ADMIN_CONFIRM_LEAVE_LIST_FAIL";

export const ADMIN_CONFIRM_LEAVE_UPDATE_REQUEST = "ADMIN_CONFIRM_LEAVE_UPDATE_REQUEST";
export const ADMIN_CONFIRM_LEAVE_UPDATE_SUCCESS = "ADMIN_CONFIRM_LEAVE_UPDATE_SUCCESS";
export const ADMIN_CONFIRM_LEAVE_UPDATE_FAIL = "ADMIN_CONFIRM_LEAVE_UPDATE_FAIL";
