export const NUTRITION_PLAN_LIST_TRAINER_REQUEST = "NUTRITION_PLAN_LIST_TRAINER_REQUEST";
export const NUTRITION_PLAN_LIST_TRAINER_SUCCESS = "NUTRITION_PLAN_LIST_TRAINER_SUCCESS";
export const NUTRITION_PLAN_LIST_TRAINER_FAIL = "NUTRITION_PLAN_LIST_TRAINER_FAIL";

export const NUTRITION_PLAN_CREATE_TRAINER_REQUEST = "NUTRITION_PLAN_CREATE_TRAINER_REQUEST";
export const NUTRITION_PLAN_CREATE_TRAINER_SUCCESS = "NUTRITION_PLAN_CREATE_TRAINER_SUCCESS";
export const NUTRITION_PLAN_CREATE_TRAINER_FAIL = "NUTRITION_PLAN_CREATE_TRAINER_FAIL";

export const NUTRITION_PLAN_UPDATE_TRAINER_REQUEST = "NUTRITION_PLAN_UPDATE_TRAINER_REQUEST";
export const NUTRITION_PLAN_UPDATE_TRAINER_SUCCESS = "NUTRITION_PLAN_UPDATE_TRAINER_SUCCESS";
export const NUTRITION_PLAN_UPDATE_TRAINER_FAIL = "NUTRITION_PLAN_UPDATE_TRAINER_FAIL";

export const NUTRITION_PLAN_DELETE_TRAINER_REQUEST = "NUTRITION_PLAN_DELETE_TRAINER_REQUEST";
export const NUTRITION_PLAN_DELETE_TRAINER_SUCCESS = "NUTRITION_PLAN_DELETE_TRAINER_SUCCESS";
export const NUTRITION_PLAN_DELETE_TRAINER_FAIL = "NUTRITION_PLAN_DELETE_TRAINER_FAIL";

export const NUTRITION_PLAN_LIST_ADMIN_REQUEST = "NUTRITION_PLAN_LIST_ADMIN_REQUEST";
export const NUTRITION_PLAN_LIST_ADMIN_SUCCESS = "NUTRITION_PLAN_LIST_ADMIN_SUCCESS";
export const NUTRITION_PLAN_LIST_ADMIN_FAIL = "NUTRITION_PLAN_LIST_ADMIN_FAIL";
