export const PROGRESS_LIST_CUSTOMER_REQUEST = "PROGRESS_LIST_CUSTOMER_REQUEST";
export const PROGRESS_LIST_CUSTOMER_SUCCESS = "PROGRESS_LIST_CUSTOMER_SUCCESS";
export const PROGRESS_LIST_CUSTOMER_FAIL = "PROGRESS_LIST_CUSTOMER_FAIL";

export const PROGRESS_CREATE_CUSTOMER_REQUEST = "PROGRESS_CREATE_CUSTOMER_REQUEST";
export const PROGRESS_CREATE_CUSTOMER_SUCCESS = "PROGRESS_CREATE_CUSTOMER_SUCCESS";
export const PROGRESS_CREATE_CUSTOMER_FAIL = "PROGRESS_CREATE_CUSTOMER_FAIL";
