export const WORKOUT_SCHEDULE_LIST_REQUEST = "WORKOUT_SCHEDULE_LIST_REQUEST";
export const WORKOUT_SCHEDULE_LIST_SUCCESS = "WORKOUT_SCHEDULE_LIST_SUCCESS";
export const WORKOUT_SCHEDULE_LIST_FAIL = "WORKOUT_SCHEDULE_LIST_FAIL";

export const WORKOUT_SCHEDULE_CREATE_REQUEST = "WORKOUT_SCHEDULE_CREATE_REQUEST";
export const WORKOUT_SCHEDULE_CREATE_SUCCESS = "WORKOUT_SCHEDULE_CREATE_SUCCESS";
export const WORKOUT_SCHEDULE_CREATE_FAIL = "WORKOUT_SCHEDULE_CREATE_FAIL";

export const WORKOUT_SCHEDULE_UPDATE_REQUEST = "WORKOUT_SCHEDULE_UPDATE_REQUEST";
export const WORKOUT_SCHEDULE_UPDATE_SUCCESS = "WORKOUT_SCHEDULE_UPDATE_SUCCESS";
export const WORKOUT_SCHEDULE_UPDATE_FAIL = "WORKOUT_SCHEDULE_UPDATE_FAIL";

export const WORKOUT_SCHEDULE_DELETE_REQUEST = "WORKOUT_SCHEDULE_DELETE_REQUEST";
export const WORKOUT_SCHEDULE_DELETE_SUCCESS = "WORKOUT_SCHEDULE_DELETE_SUCCESS";
export const WORKOUT_SCHEDULE_DELETE_FAIL = "WORKOUT_SCHEDULE_DELETE_FAIL";
