export const TIME_LIST_CUSTOMER_REQUEST = "TIME_LIST_CUSTOMER_REQUEST";
export const TIME_LIST_CUSTOMER_SUCCESS = "TIME_LIST_CUSTOMER_SUCCESS";
export const TIME_LIST_CUSTOMER_FAIL = "TIME_LIST_CUSTOMER_FAIL";

export const TIME_CREATE_CUSTOMER_REQUEST = "TIME_CREATE_CUSTOMER_REQUEST";
export const TIME_CREATE_CUSTOMER_SUCCESS = "TIME_CREATE_CUSTOMER_SUCCESS";
export const TIME_CREATE_CUSTOMER_FAIL = "TIME_CREATE_CUSTOMER_FAIL";
