export const TRAINER_LIST_REQUEST = "TRAINER_LIST_REQUEST";
export const TRAINER_LIST_SUCCESS = "TRAINER_LIST_SUCCESS";
export const TRAINER_LIST_FAIL = "TRAINER_LIST_FAIL";

export const TRAINER_LOGIN_REQUEST = "TRAINER_LOGIN_REQUEST";
export const TRAINER_LOGIN_SUCCESS = "TRAINER_LOGIN_SUCCESS";
export const TRAINER_LOGIN_FAIL = "TRAINER_LOGIN_FAIL";
export const TRAINER_LOGOUT = "TRAINER_LOGOUT";

export const TRAINER_REGISTER_REQUEST = "TRAINER_REGISTER_REQUEST";
export const TRAINER_REGISTER_SUCCESS = "TRAINER_REGISTER_SUCCESS";
export const TRAINER_REGISTER_FAIL = "TRAINER_REGISTER_FAIL";

export const TRAINER_VIEW_REQUEST = "TRAINER_VIEW_REQUEST";
export const TRAINER_VIEW_SUCCESS = "TRAINER_VIEW_SUCCESS";
export const TRAINER_VIEW_FAIL = "TRAINER_VIEW_FAIL";

export const TRAINER_UPDATE_REQUEST = "TRAINER_UPDATE_REQUEST";
export const TRAINER_UPDATE_SUCCESS = "TRAINER_UPDATE_SUCCESS";
export const TRAINER_UPDATE_FAIL = "TRAINER_UPDATE_FAIL";

export const TRAINER_DELETE_REQUEST = "TRAINER_DELETE_REQUEST";
export const TRAINER_DELETE_SUCCESS = "TRAINER_DELETE_SUCCESS";
export const TRAINER_DELETE_FAIL = "TRAINER_DELETE_FAIL";

export const TRAINER_VIEW_BY_ID_REQUEST = "TRAINER_VIEW_BY_ID_REQUEST";
export const TRAINER_VIEW_BY_ID_SUCCESS = "TRAINER_VIEW_BY_ID_SUCCESS";
export const TRAINER_VIEW_BY_ID_FAIL = "TRAINER_VIEW_BY_ID_FAIL";

export const TRAINER_UPDATE_BY_ID_REQUEST = "TRAINER_UPDATE_BY_ID_REQUEST";
export const TRAINER_UPDATE_BY_ID_SUCCESS = "TRAINER_UPDATE_BY_ID_SUCCESS";
export const TRAINER_UPDATE_BY_ID_FAIL = "TRAINER_UPDATE_BY_ID_FAIL";
