export const TRAINERLEAVE_LIST_REQUEST = "TRAINERLEAVE_LIST_REQUEST";
export const TRAINERLEAVE_LIST_SUCCESS = "TRAINERLEAVE_LIST_SUCCESS";
export const TRAINERLEAVE_LIST_FAIL = "TRAINERLEAVE_LIST_FAIL";

export const TRAINERLEAVE_CREATE_REQUEST = "TRAINERLEAVE_CREATE_REQUEST";
export const TRAINERLEAVE_CREATE_SUCCESS = "TRAINERLEAVE_CREATE_SUCCESS";
export const TRAINERLEAVE_CREATE_FAIL = "TRAINERLEAVE_CREATE_FAIL";

export const TRAINERLEAVE_UPDATE_REQUEST = "TRAINERLEAVE_UPDATE_REQUEST";
export const TRAINERLEAVE_UPDATE_SUCCESS = "TRAINERLEAVE_UPDATE_SUCCESS";
export const TRAINERLEAVE_UPDATE_FAIL = "TRAINERLEAVE_UPDATE_FAIL";

export const TRAINERLEAVE_DELETE_REQUEST = "TRAINERLEAVE_DELETE_REQUEST";
export const TRAINERLEAVE_DELETE_SUCCESS = "TRAINERLEAVE_DELETE_SUCCESS";
export const TRAINERLEAVE_DELETE_FAIL = "TRAINERLEAVE_DELETE_FAIL";
