export const WORKOUT_LIST_REQUEST = "WORKOUT_LIST_REQUEST";
export const WORKOUT_LIST_SUCCESS = "WORKOUT_LIST_SUCCESS";
export const WORKOUT_LIST_FAIL = "WORKOUT_LIST_FAIL";

export const WORKOUT_CREATE_REQUEST = "WORKOUT_CREATE_REQUEST";
export const WORKOUT_CREATE_SUCCESS = "WORKOUT_CREATE_SUCCESS";
export const WORKOUT_CREATE_FAIL = "WORKOUT_CREATE_FAIL";

export const WORKOUT_UPDATE_REQUEST = "WORKOUT_UPDATE_REQUEST";
export const WORKOUT_UPDATE_SUCCESS = "WORKOUT_UPDATE_SUCCESS";
export const WORKOUT_UPDATE_FAIL = "WORKOUT_UPDATE_FAIL";

export const WORKOUT_DELETE_REQUEST = "WORKOUT_DELETE_REQUEST";
export const WORKOUT_DELETE_SUCCESS = "WORKOUT_DELETE_SUCCESS";
export const WORKOUT_DELETE_FAIL = "WORKOUT_DELETE_FAIL";

export const WORKOUT_CUSTOMER_LIST_REQUEST = "WORKOUT_CUSTOMER_LIST_REQUEST";
export const WORKOUT_CUSTOMER_LIST_SUCCESS = "WORKOUT_CUSTOMER_LIST_SUCCESS";
export const WORKOUT_CUSTOMER_LIST_FAIL = "WORKOUT_CUSTOMER_LIST_FAIL";
